@startuml Archer Financial Class Diagram

'groups two or more similar arrows together
skinparam groupInheritance 2

'Classes
class LED 
{
    {static} Constants
    RED_PIN 12
    YELLOW_PIN 11
    GREEN_PIN 10
    ..
    {static} Variables
    String LEDState
    int LEDDelay
    int LEDErrorDelay
    unsigned long lastTimeBlinked
    unsigned long lastTimeBlinkedForError
    int blinkDelay
    ..
    {static} Methods    
    void blinkYellowByDistance()
    void controlBrightnessByLuminosity()
    void lockLEDs()
}

class PushButton 
{
    {static} Constants
    BUTTON_PIN 2
    ..
    {static} Variables
    unsigned long clickTimeCounter
    int buttonTimeDelay
    ..
    {static} Methods
    void unlockBot()
}

class UltrasonicSensor
{
    {static} Constants
    ECHO_PIN 4
    TRIGGER_PIN 3
    ..
    {static} Variables
    unsigned long lastTimeSensorTriggered
    int sensorDelay
    volatile unsigned long pulseStart
    volatile unsigned long pulseEnd
    ..
    {static} Methods
    void triggerUltrasonicSensor()
    double getUltrasonicDistance()
    void lockBot(double distance)
    void echoPinInterrupt()
}

class LCD
{
    {static} Constants
    RS_PIN A5
    E_PIN A4
    D4_PIN 6
    D5_PIN 7
    D6_PIN 8
    D7_PIN 9
    LCD_SCREEN_COUNT 4
    ..
    {static} Variables
    String[] LCDStates
    String LCDState
    LiquidCrystal lcd
    ..
    {static} Methods
    void printScreen()
    void printErrorMessageScreen()
    void printDefaultMessageScreen()
    void printDistanceScreen()
    void printLuminosityScreen()
    void printInitializingScreen()
}

class Photoresistor
{
    {static} Constants
    PHOTORESISTOR_PIN
    ..
    {static} Variables
    unsigned long lastTimeLuminosityChecked
    int luminosityDelay
    ..
    {static} Methods
    int getLuminosity()
}

class Remote
{
    {static} Constants
    IR_RECEIVE_PIN 5
    PLAY_RIGHT_BUTTON 0x5A
    UP_BUTTON 0x18
    DOWN_BUTTON 0x52
    EQ_OK_BUTTON 0x1C
    OFF_STAR_BUTTON 0x16
    ..
    {static} Methods
    void unlockBot()
    void upButtonPressed()
    void downButtonPressed()
    void changeDefaultSettings()
    void resetDefaultSettings()
}

class Setup 
{   
    {static} Methods
    void setUpLED()
    void setUpPushButton()
    void setUpUltrasonicSensor()
    void setUpLCD()
    void setUpRemote()
}